#!/usr/bin/env python3
"""
AIOS.is Materials Characterization Tools
Basic analysis tools for aerogel characterization

Usage:
    python characterization.py

This script provides basic analysis tools for aerogel samples.
Replace the sample data with your actual measurements.
"""

import numpy as np
import matplotlib.pyplot as plt
from dataclasses import dataclass
from typing import List, Tuple, Optional
import json


@dataclass
class AerogelSample:
    """Data class for aerogel sample properties"""
    name: str
    mass_dry: float  # grams
    volume: float  # cm³
    dimensions: Tuple[float, float, float]  # length, width, height (cm)
    mass_wet: Optional[float] = None  # grams (for porosity calc)


class AerogelAnalyzer:
    """Basic aerogel characterization tools"""

    def __init__(self):
        self.samples: List[AerogelSample] = []

    def add_sample(self, sample: AerogelSample):
        """Add a sample for analysis"""
        self.samples.append(sample)

    def calculate_density(self, sample: AerogelSample) -> float:
        """Calculate bulk density (g/cm³)"""
        return sample.mass_dry / sample.volume

    def calculate_porosity(self, sample: AerogelSample,
                          skeletal_density: float = 2.2) -> Optional[float]:
        """
        Calculate porosity using skeletal density
        skeletal_density: theoretical density of solid material (g/cm³)
        Default 2.2 g/cm³ is typical for silica
        """
        if sample.mass_wet is None:
            return None

        bulk_density = self.calculate_density(sample)

        # Porosity = 1 - (bulk_density / skeletal_density)
        porosity = 1 - (bulk_density / skeletal_density)
        return max(0, min(1, porosity))  # Clamp to [0,1]

    def estimate_surface_area(self, sample: AerogelSample,
                            particle_size: float = 10e-7) -> float:
        """
        Rough estimate of surface area using particle size
        particle_size in cm
        Returns surface area in m²/g
        """
        bulk_density = self.calculate_density(sample)

        # Assume spherical particles
        # Surface area per gram = (surface area per particle) / (mass per particle)
        # Surface area per particle = 4πr²
        # Mass per particle = (4/3)πr³ * density

        radius = particle_size / 2
        sa_per_particle = 4 * np.pi * radius**2
        mass_per_particle = (4/3) * np.pi * radius**3 * 2.2  # skeletal density

        sa_per_gram = sa_per_particle / mass_per_particle

        # Adjust for packing efficiency (rough estimate)
        return sa_per_gram * 0.1  # Conservative estimate

    def calculate_specific_surface_area(self, sample: AerogelSample) -> float:
        """Calculate specific surface area using geometric method"""
        # For silica aerogels, typical range 600-1000 m²/g
        # This is a rough geometric estimate
        porosity = self.calculate_porosity(sample)
        if porosity is None:
            return 800  # Typical value

        # Empirical correlation
        return 1000 * (1 - porosity) + 200

    def thermal_conductivity_estimate(self, sample: AerogelSample) -> float:
        """Estimate thermal conductivity based on density"""
        density = self.calculate_density(sample)

        # Empirical correlation for silica aerogels
        # Lower density = lower thermal conductivity
        base_conductivity = 0.015  # W/m·K for ~0.1 g/cm³
        density_factor = density / 0.1

        return base_conductivity * (density_factor ** 0.5)

    def generate_report(self, sample: AerogelSample) -> dict:
        """Generate comprehensive characterization report"""
        density = self.calculate_density(sample)
        porosity = self.calculate_porosity(sample)
        surface_area = self.calculate_specific_surface_area(sample)
        thermal_cond = self.thermal_conductivity_estimate(sample)

        report = {
            "sample_name": sample.name,
            "timestamp": "Generated by AIOS.is Materials Analyzer",
            "physical_properties": {
                "bulk_density_g_cm3": round(density, 4),
                "porosity_percent": round(porosity * 100, 1) if porosity else None,
                "volume_cm3": round(sample.volume, 2),
                "dimensions_cm": sample.dimensions
            },
            "estimated_properties": {
                "specific_surface_area_m2_g": round(surface_area, 0),
                "thermal_conductivity_W_mK": round(thermal_cond, 4)
            },
            "measurement_notes": [
                "Density calculated from mass/volume measurements",
                "Porosity assumes silica skeletal density of 2.2 g/cm³",
                "Surface area is geometric estimate - BET recommended for accuracy",
                "Thermal conductivity is empirical correlation - measure for precision"
            ],
            "recommendations": [
                "For precise surface area measurements, use BET analysis",
                "Thermal conductivity should be measured with guarded hot plate method",
                "Mechanical testing recommended for strength characterization",
                "SEM/TEM analysis suggested for microstructural evaluation"
            ]
        }

        return report

    def plot_comparison(self, property_name: str = "density"):
        """Create comparison plot of samples"""
        if not self.samples:
            print("No samples to plot")
            return

        names = [s.name for s in self.samples]
        values = []

        for sample in self.samples:
            if property_name == "density":
                values.append(self.calculate_density(sample))
            elif property_name == "porosity":
                porosity = self.calculate_porosity(sample)
                values.append(porosity if porosity else 0)
            else:
                values.append(0)

        plt.figure(figsize=(10, 6))
        plt.bar(names, values)
        plt.title(f'Aerogel Sample Comparison - {property_name.title()}')
        plt.ylabel(f'{property_name.title()}')
        plt.xticks(rotation=45, ha='right')
        plt.tight_layout()
        plt.savefig(f'aerogel_comparison_{property_name}.png', dpi=150, bbox_inches='tight')
        plt.show()


def main():
    """Example usage with sample data"""
    analyzer = AerogelAnalyzer()

    # Example sample data (replace with your measurements)
    sample1 = AerogelSample(
        name="Rice_Husk_Silica_Aerogel",
        mass_dry=0.15,  # grams
        volume=10.0,     # cm³
        dimensions=(2.0, 2.0, 2.5)  # cm
    )

    sample2 = AerogelSample(
        name="Microbial_Alginate_Aerogel",
        mass_dry=0.08,
        volume=8.0,
        dimensions=(2.0, 2.0, 2.0)
    )

    analyzer.add_sample(sample1)
    analyzer.add_sample(sample2)

    # Generate reports
    for sample in analyzer.samples:
        report = analyzer.generate_report(sample)
        print(f"\n=== Characterization Report: {sample.name} ===")
        print(json.dumps(report, indent=2))

        # Save report
        with open(f"{sample.name}_report.json", 'w') as f:
            json.dump(report, f, indent=2)

    print("
📊 Reports saved as JSON files"    print("📈 To create comparison plots, run:"    print("   analyzer.plot_comparison('density')")
    print("   analyzer.plot_comparison('porosity')")


if __name__ == "__main__":
    main()